# Generated by Django 4.0.6 on 2022-07-08 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solver', '0002_userpreferences_allowed_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='allowed_days',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='excluded_days',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('allowed', models.BooleanField(default=True)),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_preferences', to='solver.userpreferences')),
            ],
        ),
    ]
