# Generated by Django 4.0.6 on 2022-07-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_remove_userpreferences_allowed_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypreference',
            old_name='user_preference',
            new_name='user_preferences',
        ),
    ]
