# Generated by Django 4.0.6 on 2022-07-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_rename_user_preference_daypreference_user_preferences'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='daypreference',
            constraint=models.UniqueConstraint(fields=('user_preferences', 'start'), name='unique_day_preference'),
        ),
    ]
