# Generated by Django 4.0.6 on 2022-07-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0005_daypreference_unique_day_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypreference',
            old_name='allowed',
            new_name='available',
        ),
    ]
