# Generated by Django 4.0.6 on 2022-07-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0006_rename_allowed_daypreference_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='wednesday',
        ),
    ]
