# Generated by Django 4.0.6 on 2022-07-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0011_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date',
            new_name='start',
        ),
    ]
