# Generated by Django 4.0.6 on 2022-07-28 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_user_id(apps, schema):
    DayPreference = apps.get_model("solver", "DayPreference")
    for d in DayPreference.objects.all():
        d.user = d.user_preferences.user
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("solver", "0012_rename_date_assignment_start"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="daypreference",
            name="unique_day_preference",
        ),
        migrations.AddField(
            model_name="daypreference",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(copy_user_id),
        migrations.RemoveField(
            model_name="daypreference",
            name="user_preferences",
        ),
        migrations.AddConstraint(
            model_name="daypreference",
            constraint=models.UniqueConstraint(
                fields=("user_id", "start"), name="unique_day_preference"
            ),
        ),
    ]
