# Generated by Django 4.0.6 on 2022-07-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solver", "0013_remove_daypreference_unique_day_preference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
