# Generated by Django 4.0.6 on 2022-07-29 19:31

from django.db import migrations, models
import django.db.models.deletion


def assign_schedule_id(apps, schema):
    User = apps.get_model("auth", "User")
    for u in User.objects.all():
        schedules = u.schedules.all()
        day_preferences = u.day_preferences.all()
        for d in day_preferences:
            for index, s in enumerate(schedules):
                if index > 0:
                    d.pk = None
                d.schedule = s
                d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("solver", "0014_remove_userpreferences"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="daypreference",
            name="unique_day_preference",
        ),
        migrations.AddField(
            model_name="daypreference",
            name="schedule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day_preferences",
                to="solver.schedule",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_schedule_id),
        migrations.AddConstraint(
            model_name="daypreference",
            constraint=models.UniqueConstraint(
                fields=("user_id", "start", "schedule"),
                name="unique_day_preference",
            ),
        ),
    ]
