# Generated by Django 4.0.6 on 2022-07-29 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0015_remove_daypreference_unique_day_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
