# Generated by Django 4.0.6 on 2022-09-06 05:52

import datetime
from django.db import migrations


def date_range(start, end):
    current = start
    while current <= end:
        yield current
        current += datetime.timedelta(days=1)


def set_days_on_schedule(apps, schema):
    Schedule = apps.get_model("solver", "Schedule")
    Day = apps.get_model("solver", "Day")
    for schedule in Schedule.objects.all():
        dates = date_range(schedule.start, schedule.end)
        Day.objects.bulk_create(Day(schedule=schedule, start=date) for date in dates)


def create_participants(apps, schema):
    Schedule = apps.get_model("solver", "Schedule")
    Participant = apps.get_model("solver", "Participant")
    PreferredDate = apps.get_model("solver", "PreferredDate")
    DayPreference = apps.get_model("solver", "DayPreference")
    for schedule in Schedule.objects.all():
        for user in schedule.users.all():
            participant = Participant.objects.create(
                schedule=schedule, name=user.username
            )
            PreferredDate.objects.bulk_create(
                PreferredDate(participant=participant, start=day_preference.start)
                for day_preference in DayPreference.objects.filter(
                    user=user, schedule=schedule, active=True
                )
            )


class Migration(migrations.Migration):

    dependencies = [
        ("solver", "0020_participant_preferreddate_day_assigneddate_and_more"),
    ]

    operations = [
        migrations.RunPython(set_days_on_schedule),
        migrations.RunPython(create_participants),
    ]
