# Generated by Django 4.0.6 on 2022-09-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0021_auto_20220906_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayPreference',
        ),
    ]
