# Generated by Django 4.0.6 on 2022-09-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0022_delete_daypreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
