# Generated by Django 4.0.6 on 2022-09-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0023_delete_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start',
        ),
    ]
