# Generated by Django 4.0.6 on 2022-09-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0024_remove_schedule_end_remove_schedule_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='users',
        ),
    ]
